version: '3.8'

services:
  app:
    build:
      context: ./app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    depends_on:
      - mongodb
      - qdrant
      - clearml

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/data

  clearml:
    image: allegroai/clearml:latest
    container_name: clearml
    ports:
      - "8080:8080"
    environment:
      CLEARML_SERVER_HOST: "http://localhost:8080"
      CLEARML_API_ACCESS_KEY: "default"
      CLEARML_API_SECRET_KEY: "default"

volumes:
  mongodb_data:
  qdrant_data:
